skillMetadata:
  sections:
    - name: Options
      fields:
        - name: study_duration
          type: number
          label: The duration of the study interval
          value: "25"
        - name: break_duration
          type: number
          label: The duration of the break interval
          value: "5"